Задача 2
DJettt/MathMechBot pull request #16
Opened 2024-10-14 10:45 UTC by ASHGOLDOFFICIAL

# Changelog

## Общее по проекту

- Добавлены GitHub Actions с двумя простыми задачами, которые запускаются при создании PR (в том числе этого) (#9):
    - Пакетирование и запуск тестов (запускает `mvn package` и `mvn test`).
    - Проверка стиля кода.

## Платформы

- Добавлена возможность ядром отправлять кнопки (реализована на платформах Discord и Telegram) (#11):
- Добавлен общий интерфейс для ботов (#7)

## Хранение данных

- Описаны модели хранимых данных (#10, #12):
    - `User` хранит пользователя нашего бота.
    - `UserEntry` хранит зарегистрированные пользователем данные (отдельньная модель, потому что предполагается, что у одного пользователя может быть несколько таковых).
- Написан интерфейс хранилища (см. паттерн "Репозиторий") и его реализация на массиве (#10, #12). Используется для хранения объектов, описанных моделями.

## Логическое ядро

- Ядро теперь не возвращает ботам сообщения для отправки, вместо этого оно напрямую вызывает у них метод отправки сообщения (#10).
- Написано ядро основного бота по паттерну "Состояние" (#12), что позволяет вести с пользователем многошаговый диалог.
- Реализован процесс регистрации и удаления данных (#12). Данные хранятся в выше описанных хранилищах.
- Реализован процесс редактирования данных (???????????).

# Работа бота

Работа бота происходит по следующей схеме:

1. Пользователь отправляет сообщение.
1. Бот некоторой платформы его получает и отправляет ядру.
1. Ядро проверяет, есть ли данный пользователь в хранилище (условно БД).
    1. Если нет, добавляет этого пользователя в БД и присваевает ему дефолтное состояние.
1. Ядро достаёт из БД этого пользователя.
1. Ядро берёт объект, обрабатывающий сообщения для текущего состояния пользователя (этот объект -- состояние логического ядра или мини-ядро).
1. Ядро передаёт сообщение пользователя этому состоянию.
1. Состояние обрабатывает внутри сообщение: валидизирует полученные данные, сохраняет/удаляет данные в/из БД, при необходимости меняет состояние пользователя на некоторое другое.
1. Схема повторяется.

Таким образом, основное ядро выступает роутером между отдельными состояниями логического ядра (мини-ядрами). Это позволяет писать обработчики сообщений для конкретного состояния пользователя в отдельном классе сравнительно независимо друг от друга. Более подробно про работу кода читайте в #12 и комментариях к нему.

2024-10-14 15:07 UTC, DJettt approved these changes
Все классно 👍

2024-10-14 16:06 UTC, ASHGOLDOFFICIAL commented
> Все классно 👍

Дальше будет лучше.

2024-10-20 15:40 UTC, vpyzhyanov commented
Задача гарантировано принята не будет

![image](https://github.com/user-attachments/assets/712e69e8-795e-4a2d-b00a-35909af1cfcc)

2024-10-20 17:21 UTC, vpyzhyanov requested changes
Вы почему отправляете решение, которое не удовлетворяет элементарным требованиям? В этот раз я проверил, но в следующий раз даже проверять не буду

2024-10-20 17:21 UTC, vpyzhyanov commented on src/main/java/ru/urfu/Main.java
>      private static void startBot(LogicCore logicCore, String env, Class<? extends Bot> botClass) {
> Class<? extends Bot> botClass

Самое время познакомиться с полиморфизмом. Это намного проще, эффективнее и красивее. Сейчас тут оверинжиниринг, который даже непонятно зачем нужен. 

Сделайте так же как с LogicCore. Просто создайте нужный экземпляр и передайте его сюда. LogicCore надо убрать, он не нужен, он внутри бота

2024-10-20 17:21 UTC, vpyzhyanov commented on src/main/java/ru/urfu/Main.java
>      private static void startBot(LogicCore logicCore, String env, Class<? extends Bot> botClass) {
Вроде только начал смотреть и в самом первом методе уже куча проблем

![image](https://github.com/user-attachments/assets/16aa4a81-b7b1-4ab9-8cb6-f99bc2ea4ba7)

1. Проблема с расширяемостью кода. Код явно ориентирован не только на телеграмм
2. Уже написал, но повторюсь. Проблема с полиморфизмом и лишние аргументы
3. Нет никакой проблемы вызывать заранее известный вам конструктор. Тем более тут вы создали себе проблему в будущем. Класс бота обязан реализовывать указанный вами конструктор, но вы нигде это не контролируете. Да и не надо ничего это делать, в этом нет смысла.
4. Запуск бота не должен быть в интерфейсе Bot. Тут вы обязываете бота запускаться без параметров. Но почему вы решили наложить на него такие строгие требования? Не надо так. Смысла в этом тоже ноль.
5. Логирование - это очень хорошо, но использовать его надо правильно. Например в данном случае, вы осознанно решили, что нужно "глушить" ошибку и продолжать выполнение программы? Правда есть смысл работать дальше, если бот не запустился? Конечно же нет.

Мы плавно подошли к тому что метод не содержит ООП и на самом деле вообще не нужен. Особенно об этом кричит пункт 4, ибо название метода говорит, что только ради этого он и существует.

Правда ведь не стоило писать аж 20 строчек кода просто чтобы заменить этот код:

```java
        TelegramBot telegramBot = new TelegramBot(System.getenv("TGMATHMECHBOT_TOKEN"), logicCore);
        telegramBot.start();
```

Классы и методы нужны, чтобы облегчить сложные конструкции и упростить код, а не увеличить его.

2024-10-20 17:21 UTC, vpyzhyanov commented on src/main/java/ru/urfu/Main.java
>          String botToken = System.getenv(env);
кстати, неудачное имя переменной `env,` оно ни о чём не говорит. Например оно должно быть `botTokenEnvirontmentName`. 

Но правильно просто передавать **значение**, а не имя переменной

2024-10-20 17:21 UTC, vpyzhyanov commented on src/main/java/ru/urfu/Main.java
> +        final MathMechStorage storage = new MathMechStorage(new UserArrayStorage(), new UserEntryArrayStorage());
абсолютно всегда тут используются одни и те же классы. Значит их можно не устанавливать через конструктор, а инициализировать внутри конструктора по умолчанию.

2024-10-20 17:21 UTC, vpyzhyanov commented on src/main/java/ru/urfu/bots/Bot.java
>      /**
Метод start надо удалить, он для бота не нужен

2024-10-20 17:21 UTC, vpyzhyanov commented on src/main/java/ru/urfu/Main.java
>      private static void startBot(LogicCore logicCore, String env, Class<? extends Bot> botClass) {
**static запрещён!!!!**

2024-10-20 17:21 UTC, vpyzhyanov commented on src/main/java/ru/urfu/bots/DiscordBot.java
> +    private static final Logger LOGGER = LoggerFactory.getLogger(DiscordBot.class);
static запрещён!!!!

2024-10-20 17:21 UTC, vpyzhyanov commented on src/main/java/ru/urfu/bots/DiscordBot.java
> +        //TODO: проверить на возникновение исключений
надо проверить

2024-10-20 17:21 UTC, vpyzhyanov commented on src/main/java/ru/urfu/bots/DiscordBot.java
> +                .setActivity(Activity.playing("IDEA Intellij"))
каким образом бот связан со средой разработки?

2024-10-20 17:21 UTC, vpyzhyanov commented on src/main/java/ru/urfu/bots/DiscordBot.java
> +        final int maxSize = 5;
это должно быть константой

2024-10-20 17:21 UTC, vpyzhyanov commented on src/main/java/ru/urfu/bots/DiscordBot.java
> +    public void sendMessage(@NotNull LocalMessage message, @NotNull Long id) {
Переопределять JavaDoc у интерфейсов категорически запрещено! Это надругательство над полиморфизмом, сводящее его в могилу

2024-10-20 17:21 UTC, vpyzhyanov commented on src/main/java/ru/urfu/bots/DiscordBot.java
> +     * Отслеживает отправление сообщения от пользователя боту.
аналогично.

Если вам нужны свои комментарии, то напишите их в виде комментария внутри метода

2024-10-20 17:21 UTC, vpyzhyanov commented on src/main/java/ru/urfu/bots/TelegramBot.java
> +    private static final Logger LOGGER = LoggerFactory.getLogger(TelegramBot.class);
опять static!

2024-10-20 17:21 UTC, vpyzhyanov commented on src/main/java/ru/urfu/bots/TelegramBot.java
> +public final class TelegramBot implements Bot, LongPollingSingleThreadUpdateConsumer {
я смотрю вы лёгких путей не ищете. Почему не наследовались от `TelegramLongPollingBot`?

2024-10-20 17:21 UTC, vpyzhyanov commented on src/main/java/ru/urfu/bots/TelegramBot.java
> +        botsApplication = new TelegramBotsLongPollingApplication();
Из-за такого "хардкорного" решения теперь у вас бот внутри бота. Очень интересно обоснование зачем это было сделано, ну вдруг тут есть какой-то тайный смысл (хотя вряд ли)

2024-10-20 17:21 UTC, vpyzhyanov commented on src/main/java/ru/urfu/bots/TelegramBot.java
> +     * Запуск бота в отдельном потоке.
тут вы совершили страшное преступление. Поменяли логику заданную интерфейсом. Полиморфизм теперь с вами не дружит

2024-10-20 17:21 UTC, vpyzhyanov commented on src/main/java/ru/urfu/bots/TelegramBot.java
> +        new Thread(() -> {
зачем новый поток? Если что, телеграмм бот и так запускается в отдельном потоке (по крайней мере в простом и красивом варианте)

2024-10-20 17:21 UTC, vpyzhyanov commented on src/main/java/ru/urfu/bots/TelegramBot.java
> +                LOGGER.error("Bot didn't get registered and didn't run.", e);
вы сознательно "глушите" ошибку? Какой смысл продолжать, если ничего не работает?

2024-10-20 17:21 UTC, vpyzhyanov commented on src/main/java/ru/urfu/bots/TelegramBot.java
> +     * Отправление сообщения, формат которого содержится в msg.
аналогично

2024-10-20 17:21 UTC, vpyzhyanov commented on src/main/java/ru/urfu/bots/TelegramBot.java
> +            LOGGER.error("Unknown message type!");
нет никакой информации о том, что же там было. Вам на поддержке будет очень сложно понять что пошло не так. Добавьте дополнительную информацию, чтобы быстро понять что произошло. Например передайте туда `update`

2024-10-20 17:21 UTC, vpyzhyanov commented on src/main/java/ru/urfu/localobjects/LocalMessageBuilder.java
> +public final class LocalMessageBuilder {
как правило билдер помещают внутрь класса, который он создаёт, чтобы он умел обращаться к методам, к которым не могут обращаться другие, например к приватному конструктору.

2024-10-20 17:21 UTC, vpyzhyanov commented on src/main/java/ru/urfu/localobjects/LocalMessageBuilder.java
> +public final class LocalMessageBuilder {
смысла в таком билдере мало, т.к. параметра всего 2 и можно легко создать необходимые варианты конструкторов

2024-10-20 17:21 UTC, vpyzhyanov commented on src/main/java/ru/urfu/localobjects/Request.java
> +        long id,
интересно почему и в каком таком удивительном случае id может быть null. По идее не должен быть никогда

2024-10-20 17:21 UTC, vpyzhyanov commented on src/main/java/ru/urfu/logics/LogicCore.java
> +    void processMessage(@NotNull Request request);
с одной стороны удобно сгруппировать всё это в отдельный класс, но тут есть довольно существенные недостатки

1. Количество связей в программе увеличивается на единицу, что усложняет код
2. Параметров довольно мало (всего 3 штуки), что ставит под сомнение необходимость усложнения кода
3. **(очень критично)** В эту группу могут попасть параметры, которые никак сюда по смыслу не подходят, что и произошло. Но это замечание я напишут в Request

Единственный параметр, достойный выделения в отдельный класс - это Message, но это вы уже сделали.

2024-10-20 17:21 UTC, vpyzhyanov commented on src/main/java/ru/urfu/localobjects/Request.java
> +        @NotNull Bot bot
Класс называется "запрос". Но бот к запросу никакого отношения не имеет. Он занимается **отправкой** сообщения, а это не запрос, а **ответ**. Нарушена логика и читаемость кода сильно снижена.

Нужно убрать это поле из этого класса

2024-10-20 17:21 UTC, vpyzhyanov commented on src/main/java/ru/urfu/logics/mathmechbot/Constants.java
> +    public final static LocalButton NO_BUTTON = new LocalButton("Неа", DECLINE_COMMAND);
1. static запрещён
2. Срочно надо вспомнить русский язык

2024-10-20 17:21 UTC, vpyzhyanov commented on src/main/java/ru/urfu/logics/mathmechbot/Constants.java
> +     * Приватный конструктор для класса-утилит.
в этом классе нет ни одной утилиты

2024-10-20 17:21 UTC, vpyzhyanov commented on src/main/java/ru/urfu/logics/mathmechbot/Constants.java
> +            .text("Сперва нужно зарегистрироваться.").build();
вот посмотрите как вы усложнили код неуместным использование шаблона, вместо того, чтобы написать так:

`LocalMessage ASK_FOR_REGISTRATION = new LocalMessage("Сперва нужно зарегистрироваться.");`

2024-10-20 17:21 UTC, vpyzhyanov commented on src/main/java/ru/urfu/logics/mathmechbot/MathMechBotCore.java
> + * Логическое ядро бота, обрабатывающего сообщения Telegram-каналов на предмет упоминания студентов.<br/>
никаких связей с Telegram быть не должно

2024-10-20 17:21 UTC, vpyzhyanov commented on src/main/java/ru/urfu/logics/mathmechbot/MathMechBotCore.java
> +            assert getStorage().getUsers().get(request.id()).isPresent();
1. почему вы не доверяете сами себе? В предыдущей строчке вы положили значение. Поэтому проверка никогда не сработает. Такая проверка используется, когда заранее неизвестно что может прийти на **вход** метода
2. Вы перепутали тест и основной код

2024-10-20 17:21 UTC, vpyzhyanov commented on src/main/java/ru/urfu/logics/mathmechbot/MathMechBotCore.java
> +        final User user = getStorage().getUsers().get(request.id()).get();
а может не будем дублировать код? И тем более не будем по несколько раз обращаться к хранилищу данных за одним и тем же?

```java
        UserStorage userStorage = getStorage().getUsers();
        final User user = userStorage.get(request.id())
                .orElseGet(() -> {
                    User newUser = new User(request.id(), MathMechBotUserState.DEFAULT);
                    userStorage.add(newUser);
                    return newUser;
                });
```

2024-10-20 17:21 UTC, vpyzhyanov commented on src/main/java/ru/urfu/logics/mathmechbot/MathMechBotCore.java
> +    public MathMechStorage getStorage() {
хм... инкапсуляция вышла погулять.... есть подозрение что необходимости в этом нет

2024-10-20 17:21 UTC, vpyzhyanov commented on src/main/java/ru/urfu/logics/mathmechbot/MathMechBotCore.java
> +        currentState.processMessage(this, request);
и очень подозрительно, что логика бота пошла в обработку состояния. Уже сейчас очевидно, что ООП тут и не пахнет, т.к. работа одного частного состояния требует общей логики. Это означает, что код сильно связан друг с другом. Например, чтобы изменить работу общей логики, вам придётся переписывать **каждое** состояние, которых может быть тысяча.

2024-10-20 17:21 UTC, vpyzhyanov commented on src/main/java/ru/urfu/logics/mathmechbot/models/UserBuilder.java
> +    public UserBuilder(@NotNull Long id, @NotNull MathMechBotUserState currentState) {
а тут вообще смысла в билдере не было никогда. Он ничем от обычного конструктора не отличается. Все поля обязательные.

2024-10-20 17:21 UTC, vpyzhyanov commented on src/main/java/ru/urfu/logics/mathmechbot/models/UserEntry.java
> +    public String toHumanReadable() {
а вот это очень хорошо! Правильно, что не стали использовать для этого toString(). Огромный лайк!

2024-10-20 17:21 UTC, vpyzhyanov commented on src/main/java/ru/urfu/logics/mathmechbot/models/UserEntry.java
> +public record UserEntry(
очень интересно, как может случиться так, что у пользователя будет несколько таких объектов?

2024-10-20 17:21 UTC, vpyzhyanov commented on src/main/java/ru/urfu/logics/mathmechbot/models/UserEntryBuilder.java
> +public final class UserEntryBuilder {
должен быть внутренним классом

2024-10-20 17:21 UTC, vpyzhyanov commented on src/main/java/ru/urfu/logics/mathmechbot/states/DefaultState.java
> +    public void processMessage(@NotNull MathMechBotCore context, @NotNull Request request) {
Похоже ваша цель максимально запутать разработчиков. Ведь нет лучшего средства, чем называть вещи другими именами, например MathMechBotCore называть context.

2024-10-20 17:21 UTC, vpyzhyanov commented on src/main/java/ru/urfu/logics/mathmechbot/states/DefaultState.java
> +            context.getStorage().getUsers().changeUserState(request.id(), MathMechBotUserState.REGISTRATION_NAME);
ого, вот это да, то есть любая команда имеет полный доступ к данным абсолютно всех пользователей. Достаточно забыть сделать санитайзинг запроса и можно выполнить полное удаление данных)))

Конечно же так делать нельзя, как минимум пользователь должен работать только со своим состоянием. А если необходимо управлять чужим, то должен быть отдельный класс "хранилище данных", которое будет контролировать этот процесс

2024-10-20 17:21 UTC, vpyzhyanov commented on src/main/java/ru/urfu/logics/mathmechbot/states/DefaultState.java
> +            final LocalMessage msg = DeletionConfirmationState.INSTANCE.enterMessage(context, request);
static запрещён! Следовательно синглтон тоже

2024-10-20 17:21 UTC, vpyzhyanov commented on src/main/java/ru/urfu/logics/mathmechbot/states/MathMechBotState.java
> +     * TODO: сделать умнее.
что значит умнее? Пишите конкретно

2024-10-20 17:21 UTC, vpyzhyanov commented on src/main/java/ru/urfu/logics/mathmechbot/states/deletion/DeletionConfirmationState.java
> +    INSTANCE;
нельзя. Тем более состояние синглтоном быть не может

2024-10-20 17:21 UTC, vpyzhyanov commented on src/main/java/ru/urfu/logics/mathmechbot/states/deletion/DeletionConfirmationState.java
> +    private final static Logger LOGGER = LoggerFactory.getLogger(DeletionConfirmationState.class);
нельзя

2024-10-20 17:21 UTC, vpyzhyanov commented on src/main/java/ru/urfu/logics/mathmechbot/states/deletion/DeletionConfirmationState.java
> +        context.getStorage().getUsers().changeUserState(request.id(), MathMechBotUserState.DEFAULT);
надо срочно учиться создавать переменные. Иначе вы уточните в дублируемом коде

2024-10-20 17:21 UTC, vpyzhyanov commented on src/main/java/ru/urfu/logics/mathmechbot/states/editing/EditingFullNameState.java
> +    INSTANCE;
все остальные тоже

2024-10-20 17:21 UTC, vpyzhyanov commented on src/main/java/ru/urfu/logics/mathmechbot/states/editing/EditingFullNameState.java
> +        // TODO: Проверить более сложные имена, содержащие дефисы или несколько слов.
надо проверить и убрать комментарий

2024-10-20 17:21 UTC, vpyzhyanov commented on src/main/java/ru/urfu/logics/mathmechbot/states/editing/EditingFullNameState.java
> +        context.getStorage().getUserEntries().changeUserEntryName(request.id(), strings.get(1));
срочно учимся создавать переменные

2024-10-20 17:21 UTC, vpyzhyanov commented on src/main/java/ru/urfu/storages/ArrayStorage.java
> +    private final ArrayList<T> array;
используйте интерфейсы

2024-10-20 17:21 UTC, vpyzhyanov commented on src/main/java/ru/urfu/logics/mathmechbot/storages/UserStorage.java
> +        update(new UserBuilder(id, state).build());
некорректно так использовать дефолтные методы, т.к. по сути тут вы написали **реализацию**. Зачем тогда создавали интерфейс?

2024-10-20 17:21 UTC, vpyzhyanov commented on src/main/java/ru/urfu/logics/mathmechbot/storages/UserEntryStorage.java
> +    default void changeUserEntryNameSurname(@NotNull Long id, @NotNull List<String> strings) {
не надо путать интерфейс с реализацией

Сразу видно, что увлекаетесь спрингом. Нельзя бездумно переносить шаблоны из спринга на обычный код. ООП тут точно не будет.

2024-10-20 17:21 UTC, vpyzhyanov commented on src/main/java/ru/urfu/storages/Identifiable.java
> +    I id();
обычно методы получения данных начинаются с get, т.е. `getId()`

2024-10-20 17:21 UTC, vpyzhyanov commented on src/main/java/ru/urfu/storages/Storage.java
> +    void add(T member) throws IllegalArgumentException;
нужно в JavaDoc описать это исключение и в каком случае оно произойдёт

2024-10-20 17:21 UTC, vpyzhyanov commented on src/test/java/ru/urfu/logics/DummyBot.java
> +        outcomingMessageList = new Stack<>();
стек? Вы уверены?

2024-10-20 17:21 UTC, vpyzhyanov commented on src/test/java/ru/urfu/logics/EchoBotCoreTest.java
> +final class EchoBotCoreTest {
зачем? Просто удалите это логику, она не нужна

2024-10-20 17:21 UTC, vpyzhyanov commented on src/test/java/ru/urfu/logics/mathmechbot/DeleteCommandTest.java
> +    @DisplayName("Нажата кнопка 'Неа' во время подтверждения удаления данных")
ещё и в тесте зафиксировать незнание русского языка

2024-10-20 17:21 UTC, vpyzhyanov commented on src/test/java/ru/urfu/logics/mathmechbot/TestConstants.java
> +    public final static LocalMessage DECLINE_MESSAGE = new LocalMessageBuilder().text(DECLINE_COMMAND).build();
запрещено

2024-10-20 17:21 UTC, vpyzhyanov commented on src/test/java/ru/urfu/logics/mathmechbot/TestUtils.java
> +        final ArrayList<LocalMessage> messages = new ArrayList<>(List.of(
1. Используйте интерфейсы
2. Пощадите оперативную память и не создавайте 2 абсолютно одинаковые коллекции

2024-10-20 17:21 UTC, vpyzhyanov commented on src/test/java/ru/urfu/logics/mathmechbot/editing/EditingTest.java
> +    User currentUser;
отсутствует инкапсуляция

2024-10-20 17:21 UTC, vpyzhyanov commented on src/test/java/ru/urfu/logics/mathmechbot/editing/EditingTest.java
> +                storage.getUsers().get(0L).orElseThrow());
@по хорошему тут вы не должны иметь доступ к хранилищу данных. Значит в инкапсуляции жирная дыра

Состояния - это детали реализации, о которых вообще никто знать не должен, даже тест

2024-10-20 17:21 UTC, vpyzhyanov commented on src/test/java/ru/urfu/logics/mathmechbot/editing/EditingTest.java
> +                new UserBuilder(0L, MathMechBotUserState.EDITING_FULL_NAME).build(),
я про это рассказывал на лекции. Самый первый антипример. Вы не должны использовать внутренние классы для проверки. Тут ситуация чуть сложнее, но суть та же

2024-10-20 17:42 UTC, ASHGOLDOFFICIAL commented on src/main/java/ru/urfu/Main.java
>      private static void startBot(LogicCore logicCore, String env, Class<? extends Bot> botClass) {
8683a95fc27249233d9ef8979e6960451931bc6a

Буду прикладывать коммиты с решением проблемы, что отслеживать, что уже решено.

2024-10-20 17:43 UTC, ASHGOLDOFFICIAL commented on src/main/java/ru/urfu/Main.java
>          String botToken = System.getenv(env);
8683a95fc27249233d9ef8979e6960451931bc6a

2024-10-20 17:43 UTC, ASHGOLDOFFICIAL commented on src/main/java/ru/urfu/bots/Bot.java
>      /**
8683a95fc27249233d9ef8979e6960451931bc6a

2024-10-20 17:43 UTC, ASHGOLDOFFICIAL commented on src/main/java/ru/urfu/Main.java
>      private static void startBot(LogicCore logicCore, String env, Class<? extends Bot> botClass) {
8683a95fc27249233d9ef8979e6960451931bc6a

2024-10-20 17:46 UTC, ASHGOLDOFFICIAL commented on src/main/java/ru/urfu/bots/TelegramBot.java
> +public final class TelegramBot implements Bot, LongPollingSingleThreadUpdateConsumer {
Примеры из документации используют `LongPollingSingleThreadUpdateConsumer`. `TelegramLongPollingBot` обычно упоминается в Интернет-примерах. Было решено использовать то, что использует документация, а не люди со сторонних сайтов.

2024-10-20 17:46 UTC, ASHGOLDOFFICIAL commented on src/main/java/ru/urfu/Main.java
> +        final MathMechStorage storage = new MathMechStorage(new UserArrayStorage(), new UserEntryArrayStorage());
ac5b97a15c34ae277e6b9640ee9e5fc5342bf95b

2024-10-20 17:56 UTC, ASHGOLDOFFICIAL commented on src/main/java/ru/urfu/localobjects/LocalMessageBuilder.java
> +public final class LocalMessageBuilder {
Параллельно ведутся попытки научить LocalMessage хранить картинки и прочие прикреплённые медиа-файлы. Билдер используется, чтобы потом весь код не переписывать, расширяя аргументы конструктора.

2024-10-20 18:12 UTC, ASHGOLDOFFICIAL commented on src/main/java/ru/urfu/bots/DiscordBot.java
> +    private static final Logger LOGGER = LoggerFactory.getLogger(DiscordBot.class);
169d35feaaacbbd1b6c524e36d428dfef39701ea

2024-10-20 18:13 UTC, ASHGOLDOFFICIAL commented on src/main/java/ru/urfu/bots/DiscordBot.java
> +                .setActivity(Activity.playing("IDEA Intellij"))
e038826d61cbfd8fed3e674f831d98b0a3758105

2024-10-20 18:16 UTC, ASHGOLDOFFICIAL commented on src/main/java/ru/urfu/bots/DiscordBot.java
> +        final int maxSize = 5;
9bf39508ef1226009097078afcdd872e6d3315c0

2024-10-20 18:16 UTC, ASHGOLDOFFICIAL commented on src/main/java/ru/urfu/bots/DiscordBot.java
> +    public void sendMessage(@NotNull LocalMessage message, @NotNull Long id) {
9bf39508ef1226009097078afcdd872e6d3315c0

2024-10-20 18:17 UTC, ASHGOLDOFFICIAL commented on src/main/java/ru/urfu/bots/DiscordBot.java
> +     * Отслеживает отправление сообщения от пользователя боту.
9bf39508ef1226009097078afcdd872e6d3315c0

2024-10-20 18:17 UTC, ASHGOLDOFFICIAL commented on src/main/java/ru/urfu/bots/TelegramBot.java
> +    private static final Logger LOGGER = LoggerFactory.getLogger(TelegramBot.class);
169d35feaaacbbd1b6c524e36d428dfef39701ea

2024-10-20 18:21 UTC, ASHGOLDOFFICIAL commented on src/main/java/ru/urfu/bots/TelegramBot.java
> +        new Thread(() -> {
Не запускается. Как минимум, в `LongPollingSingleThreadUpdateConsumer` он запускается в `main` потоке, не давая запуститься DiscordBot. Выбор  `LongPollingSingleThreadUpdateConsumer` был описан в соответвующем замечании.

2024-10-20 18:28 UTC, ASHGOLDOFFICIAL commented on src/main/java/ru/urfu/bots/TelegramBot.java
> +            LOGGER.error("Unknown message type!");
8cdd9817b35393d3bbc2bbd130e96fe795f8e455

2024-10-20 18:28 UTC, ASHGOLDOFFICIAL commented on src/main/java/ru/urfu/bots/TelegramBot.java
> +     * Отправление сообщения, формат которого содержится в msg.
8cdd9817b35393d3bbc2bbd130e96fe795f8e455

2024-10-20 18:29 UTC, ASHGOLDOFFICIAL commented on src/main/java/ru/urfu/bots/TelegramBot.java
> +                LOGGER.error("Bot didn't get registered and didn't run.", e);
DiscordBot может запуститься и работать без TelegramBot. Если не запустятся оба, то программа закончит исполннение, не создав ни одного потока.

8cdd9817b35393d3bbc2bbd130e96fe795f8e455

2024-10-20 18:29 UTC, ASHGOLDOFFICIAL commented on src/main/java/ru/urfu/bots/TelegramBot.java
> +     * Запуск бота в отдельном потоке.
8cdd9817b35393d3bbc2bbd130e96fe795f8e455

2024-10-20 18:36 UTC, ASHGOLDOFFICIAL commented on src/main/java/ru/urfu/localobjects/LocalMessageBuilder.java
> +public final class LocalMessageBuilder {
В таком случае нужно делать весь внутренний класс static, либо делать статичный геттер билдера. Что-то вроде:

```java
public static LocalMessageBuilder builder() {
    return new LocalMessageBuilder();
}
```

В противном случае придётся создавать LocalMessage, чтобы создать LocalMessageBuilder, что убивает смысл билдера (ибо объект уже сделан). Вы на паре запретили использовать static для этих целей.

2024-10-20 18:40 UTC, ASHGOLDOFFICIAL commented on src/main/java/ru/urfu/localobjects/Request.java
> +        long id,
30a195ef9af888c47c5eb0fdd585a73848db06de

Полагаю, это может быть достигнуто путём приминения обёртки, но я не смог придумать как именно.

2024-10-20 18:44 UTC, ASHGOLDOFFICIAL commented on src/main/java/ru/urfu/logics/LogicCore.java
> +    void processMessage(@NotNull Request request);
Список аргументов становился слишком велик (в плане длины строчки). Желательно было у всех методов нынче принимающих Request оставлять одинаковые названия для переменных (для единообразия кода), приходилось вручную следить за этим. Поэтому было решено объединить эти аргументы, которые всегда ходили вместе, в один класс.

Пока не решаю проблему, подожду Артёма.

2024-10-20 18:48 UTC, ASHGOLDOFFICIAL commented on src/main/java/ru/urfu/localobjects/Request.java
> +        @NotNull Bot bot
Не понимаю, почему это ответ. Request -- это запрос бота ядру обработать полученное сообщение. Содержит минимум нужных для этого аргументов: само сообщение (чтобы понять что обрабатывать), id отправителя, bot принявший сообщение (нужен для того, чтобы в дальнейшем понимать, с какой платформы пришло сообщение. От этого как минимум трактовка id может отличаться). Поэтому bot тут нужен пока что для понимания, откуда сообщение пришло.

Жду Артёма.

2024-10-20 18:49 UTC, ASHGOLDOFFICIAL commented on src/main/java/ru/urfu/logics/mathmechbot/Constants.java
> +    public final static LocalButton NO_BUTTON = new LocalButton("Неа", DECLINE_COMMAND);
d1f4d6609c17ede56cf9fea6c1d3e20d3b3130cb

2024-10-20 18:50 UTC, ASHGOLDOFFICIAL commented on src/main/java/ru/urfu/logics/mathmechbot/Constants.java
> +     * Приватный конструктор для класса-утилит.
169d35feaaacbbd1b6c524e36d428dfef39701ea

IDEA называла классы со статическими полями так, если не ошибаюсь.

2024-10-20 18:52 UTC, ASHGOLDOFFICIAL commented on src/main/java/ru/urfu/logics/mathmechbot/MathMechBotCore.java
> + * Логическое ядро бота, обрабатывающего сообщения Telegram-каналов на предмет упоминания студентов.<br/>
Наш бот на уровне идеи парсит Telegram-каналы. Парсить другие ресурсы изначально не предполагалось. Дождусь Артёма.

2024-10-20 18:57 UTC, ASHGOLDOFFICIAL commented on src/main/java/ru/urfu/logics/mathmechbot/MathMechBotCore.java
> +        final User user = getStorage().getUsers().get(request.id()).get();
99cf402ce1dc15aa991a50d42f11c3d470675ad6

2024-10-20 18:59 UTC, ASHGOLDOFFICIAL commented on src/main/java/ru/urfu/logics/mathmechbot/MathMechBotCore.java
> +            assert getStorage().getUsers().get(request.id()).isPresent();
99cf402ce1dc15aa991a50d42f11c3d470675ad6

assert был добавлен для IDEA, которая думала, что пользователь всё равно может отсутствовать.

2024-10-20 19:01 UTC, ASHGOLDOFFICIAL commented on src/main/java/ru/urfu/logics/mathmechbot/MathMechBotCore.java
> +    public MathMechStorage getStorage() {
Если вы про геттеры хранилищ, то я вам об этом говорил. Вы мне ещё показывали попытку сделать хранилище null-ом, что не вышло, так как поле -- final. В конце концов вы всё равно сказали, что нужно инкапсулировать, потому что это правильно. Исправлять пока не буду -- дождусь окончательного ответа по этому поводу.

2024-10-20 19:03 UTC, ASHGOLDOFFICIAL commented on src/main/java/ru/urfu/logics/mathmechbot/models/UserBuilder.java
> +    public UserBuilder(@NotNull Long id, @NotNull MathMechBotUserState currentState) {
Изначально полей было 4, два необязательных (telegramId, discordId). Исправлять везде конструкторы было болезненным опытом, поэтому было решено создать builder. Когда в дальнейшем класс будет расширяться (например, полями isBanned или isAdmin), билдер позволит не изменять код везде и не плодить конструкторов.

2024-10-20 19:05 UTC, ASHGOLDOFFICIAL commented on src/main/java/ru/urfu/logics/mathmechbot/models/UserEntry.java
> +    public String toHumanReadable() {
toString() уже определён рекордой. Плюс, toString() выводит все поля, что удобно для дебага, в то время как toHumanReadable() выводит только основную информацию для удобства чтения.

2024-10-20 19:06 UTC, ASHGOLDOFFICIAL commented on src/main/java/ru/urfu/logics/mathmechbot/models/UserEntry.java
> +public record UserEntry(
Описано в одной из следующих задач. Мы планируем позволить пользователю подписываться на упоминания нескольких лиц. Полезно старостам и кураторам.

2024-10-20 19:07 UTC, ASHGOLDOFFICIAL commented on src/main/java/ru/urfu/logics/mathmechbot/models/UserEntryBuilder.java
> +public final class UserEntryBuilder {
Пока не вижу способов сделать это без static. Пока думать буду.

2024-10-20 19:08 UTC, ASHGOLDOFFICIAL commented on src/main/java/ru/urfu/logics/mathmechbot/states/DefaultState.java
> +    public void processMessage(@NotNull MathMechBotCore context, @NotNull Request request) {
context -- устоявшейся термин в паттерне State. Наименование шло согласно паттерну. Жду Артёма для обсуждения.

2024-10-20 19:10 UTC, ASHGOLDOFFICIAL commented on src/main/java/ru/urfu/logics/mathmechbot/states/MathMechBotState.java
> +     * TODO: сделать умнее.
Мне не нравится, что enterMessage() -- это целый метод, возвращающий в большинстве случаев статичный объект. Избавился от этого с помощью FSM, которую написал.

2024-10-20 19:14 UTC, ASHGOLDOFFICIAL commented on src/main/java/ru/urfu/logics/mathmechbot/storages/UserStorage.java
> +        update(new UserBuilder(id, state).build());
Эти реализации являются композицией методов, определённых в Storage. Реализация Storage влечёт за собой реализацию этих методов. Без реализации Storage эти методы ничего не делают. При этом тот факт, что ArrayStorage extends Storage обязывает эти методы реализовать.

2024-10-20 19:18 UTC, ASHGOLDOFFICIAL commented on src/main/java/ru/urfu/logics/mathmechbot/storages/UserEntryStorage.java
> +    default void changeUserEntryNameSurname(@NotNull Long id, @NotNull List<String> strings) {
Никто из нас со Spring'ом не работал. Поэтому не понимаю, о каких шаблоннах идёт речь.

Дополнительные методы в UserEntryStorage по редактированию отдельных полей были добавлены, так как я считаю, что за изменение полей должно отвечать хранилище. Ну, в случае с БД, мы данные редактируем в ней, а не вне её. Изменение выгруженных данных не влечёт изменения их в постоянном хранилище. Только если менять их напрямую в БД они будут меняться. Поэтому эти методы и были назначены Storage'ам, как часть их ответственности.

2024-10-20 19:21 UTC, ASHGOLDOFFICIAL commented on src/main/java/ru/urfu/storages/Identifiable.java
> +    I id();
673483a0e3d19909e35722c885b84f79c7716f3f

2024-10-20 19:23 UTC, ASHGOLDOFFICIAL commented on src/main/java/ru/urfu/storages/Storage.java
> +    void add(T member) throws IllegalArgumentException;
9e14d4151ee8f955788690923204ed17a97400dd

2024-10-20 19:24 UTC, ASHGOLDOFFICIAL commented on src/main/java/ru/urfu/storages/ArrayStorage.java
> +    private final ArrayList<T> array;
ArrayStorage -- это реализация Storage на массиве. Почему это должно быть интерфейсом?

2024-10-20 19:25 UTC, ASHGOLDOFFICIAL commented on src/test/java/ru/urfu/logics/EchoBotCoreTest.java
> +final class EchoBotCoreTest {
c7bb4747ad69050adda85e75ef6650e730fe219f

2024-10-20 19:29 UTC, ASHGOLDOFFICIAL commented on src/test/java/ru/urfu/logics/mathmechbot/DeleteCommandTest.java
> +    @DisplayName("Нажата кнопка 'Неа' во время подтверждения удаления данных")
1cb7e79d2f3a53494b704e22488489648cff6eeb

Неформальная форма была умышленно, так как наша целевая аудитория -- студенты. Использование неформальных форм делает бота хотя сколько-то приближенным к целевой аудитории.

2024-10-20 19:46 UTC, ASHGOLDOFFICIAL commented on src/test/java/ru/urfu/logics/mathmechbot/TestConstants.java
> +    public final static LocalMessage DECLINE_MESSAGE = new LocalMessageBuilder().text(DECLINE_COMMAND).build();
1fdadb9634c4a9202eccd4b01eac4bc3e28bbe6c

2024-10-20 19:49 UTC, ASHGOLDOFFICIAL commented on src/test/java/ru/urfu/logics/mathmechbot/editing/EditingTest.java
> +    User currentUser;
612b8aef67d77a8f23e2d05cb43bd2e89d5d69a5

Артём, проверь, нигде ли я не забыл добавить private.

2024-10-20 19:57 UTC, ASHGOLDOFFICIAL commented on src/main/java/ru/urfu/logics/mathmechbot/states/editing/EditingFullNameState.java
> +    INSTANCE;
c120587db49c91c8a9584d404a80511aa171ebed

2024-10-20 19:57 UTC, ASHGOLDOFFICIAL commented on src/main/java/ru/urfu/logics/mathmechbot/states/deletion/DeletionConfirmationState.java
> +    private final static Logger LOGGER = LoggerFactory.getLogger(DeletionConfirmationState.class);
c120587db49c91c8a9584d404a80511aa171ebed

2024-10-20 19:58 UTC, ASHGOLDOFFICIAL commented on src/main/java/ru/urfu/logics/mathmechbot/states/deletion/DeletionConfirmationState.java
> +    INSTANCE;
c120587db49c91c8a9584d404a80511aa171ebed

2024-10-20 19:58 UTC, ASHGOLDOFFICIAL commented on src/main/java/ru/urfu/logics/mathmechbot/states/DefaultState.java
> +            final LocalMessage msg = DeletionConfirmationState.INSTANCE.enterMessage(context, request);
c120587db49c91c8a9584d404a80511aa171ebed

2024-10-20 20:02 UTC, ASHGOLDOFFICIAL commented on src/main/java/ru/urfu/logics/mathmechbot/states/DefaultState.java
> +            context.getStorage().getUsers().changeUserState(request.id(), MathMechBotUserState.REGISTRATION_NAME);
Я честно не понял, что не так. Во время регистрации просто смотрится, есть ли у данного пользователя хоть какая-то запись. Если нет, мы кидаем его в регистрацию. Я не вижу того, где бы пользователь работал не со своим состоянием. Артём, спасай.

2024-10-20 20:15 UTC, ASHGOLDOFFICIAL commented on src/main/java/ru/urfu/logics/mathmechbot/states/deletion/DeletionConfirmationState.java
> +        context.getStorage().getUsers().changeUserState(request.id(), MathMechBotUserState.DEFAULT);
688199873dd6cd7b5d5c5a372a83d747c653fc18

2024-10-20 20:18 UTC, ASHGOLDOFFICIAL commented on src/main/java/ru/urfu/bots/DiscordBot.java
> +        //TODO: проверить на возникновение исключений
Оставляю Артёму.

2024-10-20 20:41 UTC, ASHGOLDOFFICIAL commented on src/main/java/ru/urfu/bots/TelegramBot.java
> +public final class TelegramBot implements Bot, LongPollingSingleThreadUpdateConsumer {
7fa4593e159c3a0c29937f5da70a5b6f8b9748ad (хэш коммита в https://github.com/rubenlagus/TelegramBots)

Вообще, есть подозрения, что `TelegramLongPollingBot` deprecated. Подтверждений найти не могу, но автор удалил папку с этим классом в коммите с хэшем, указанным выше. Возможно, он был куда-то перенесён, но я не могу найти куда. В любом случае, если в документации используют `LongPollingSingleThreadUpdateConsumer`, то думаю, что не просто так.

2024-10-20 21:01 UTC, ASHGOLDOFFICIAL commented on src/main/java/ru/urfu/bots/TelegramBot.java
> +        botsApplication = new TelegramBotsLongPollingApplication();
`TelegramBotsLongPollingApplication` и `LongPollingSingleThreadUpdateConsumer` -- это два разных класса, у которых нет ни общих потомков, ни общих интерфейсов. Поэтому честно не вижу проблем. 

Если я правильно понял, что автор библиотеки хотел, то:
`LongPollingSingleThreadUpdateConsumer` -- это обработчик апдейтов от Telegram.
`TelegramBotsLongPollingApplication` -- это класс, отвечающий за регистрацию и запуск реализаций `LongPollingUpdateConsumer`.

Поэтому прошу уточнить, в чём проблема создания `TelegramBotsLongPollingApplication` внутри наследника `LongPollingUpdateConsumer`, если он используется для старта лишь одного единственного (этого же) `LongPollingUpdateConsumer`.

2024-10-20 21:08 UTC, ASHGOLDOFFICIAL commented on src/main/java/ru/urfu/logics/mathmechbot/MathMechBotCore.java
> +        currentState.processMessage(this, request);
Состояние диктует то, как бот должен обрабатывать сообщение. Поэтому контекст передаёт обработку сообщения нужному состоянию. Не совсем понимаю, где состоянию требуется общая логика. Подожду Артёма.

Вообще, логика работы с состояниями будет переписана в третьем таске с введением FSM, если вы это согласуете, потому что пока я тоже не удовлетворён тем, как всё организовано (но не уверен, что тем же, что и вы). В частности переходы в FSM будут диктовать, откуда в какое состояние можно перейти и что в процессе нужно сделать.

2024-10-20 21:09 UTC, ASHGOLDOFFICIAL commented on src/main/java/ru/urfu/logics/mathmechbot/states/editing/EditingFullNameState.java
> +        context.getStorage().getUserEntries().changeUserEntryName(request.id(), strings.get(1));
688199873dd6cd7b5d5c5a372a83d747c653fc18

2024-10-20 21:10 UTC, ASHGOLDOFFICIAL commented on src/main/java/ru/urfu/logics/mathmechbot/storages/UserStorage.java
> +        update(new UserBuilder(id, state).build());
Артём, оставлю тебе этот вопрос на решение.

2024-10-20 21:13 UTC, ASHGOLDOFFICIAL commented on src/test/java/ru/urfu/logics/DummyBot.java
> +        outcomingMessageList = new Stack<>();
24392b00ab844dd63a42d2c842fc5e65db62ec1e

Изначально думал, что раз мы в большинстве случаев достаёт только последнее сообщение, можно использовать стек. Потом я об этом забыл. И фактически мы не только последние сообщения доставали. Исправил, в общем-то.

2024-10-20 21:24 UTC, ASHGOLDOFFICIAL commented on src/test/java/ru/urfu/logics/mathmechbot/TestUtils.java
> +        final ArrayList<LocalMessage> messages = new ArrayList<>(List.of(
4426662008b88ecac3edee1c8725a254d20c4200

2024-10-20 21:25 UTC, ASHGOLDOFFICIAL commented on src/test/java/ru/urfu/logics/mathmechbot/editing/EditingTest.java
> +                storage.getUsers().get(0L).orElseThrow());
Слишком большая проблема, чтобы исправлять одному. Сперва проконсультируюсь с Артёмом.

2024-10-20 21:26 UTC, ASHGOLDOFFICIAL commented on src/test/java/ru/urfu/logics/mathmechbot/editing/EditingTest.java
> +                new UserBuilder(0L, MathMechBotUserState.EDITING_FULL_NAME).build(),
Артём, надо исправить тесты.

2024-10-20 21:42 UTC, ASHGOLDOFFICIAL commented on src/main/java/ru/urfu/storages/ArrayStorage.java
> +    private final ArrayList<T> array;
4613e044bfcad80a6ad3d749ec82070bce1c72b4

Всё, я понял, что вы имели в виду. GitHub, который показывает сразу 4 строки ввёл меня в заблуждение.

2024-10-20 23:01 UTC, ASHGOLDOFFICIAL commented on src/main/java/ru/urfu/bots/DiscordBot.java
> +                .setActivity(Activity.playing("IDEA Intellij"))
Изначально подразумевалось как небольшой элемент юмора.

2024-10-20 23:07 UTC, ASHGOLDOFFICIAL commented on src/main/java/ru/urfu/bots/TelegramBot.java
> +public final class TelegramBot implements Bot, LongPollingSingleThreadUpdateConsumer {
![image](https://github.com/user-attachments/assets/29236312-09eb-4671-85c0-2ec50fbb6b95)

https://rubenlagus.github.io/TelegramBotsDocumentation/how-to-update-7.html#migrating-your-existing-longpolling-bots

Нашёл подтверждение. `TelegramLongPollingBot` можно считать deprecated.

2024-10-21 00:35 UTC, DJettt commented on src/main/java/ru/urfu/logics/mathmechbot/MathMechBotCore.java
> + * Логическое ядро бота, обрабатывающего сообщения Telegram-каналов на предмет упоминания студентов.<br/>
Все так. Бот будет парсить сообщение из Telegram-канала МатМеха, анализировать его и отправлять результат обработки в тот мессенджер, который укажет пользователь из доступных.

2024-10-21 00:37 UTC, DJettt commented on src/main/java/ru/urfu/logics/mathmechbot/MathMechBotCore.java
> +            assert getStorage().getUsers().get(request.id()).isPresent();
Это было сделано буквально для уменьшения количества warning-ов и подчеркиваний со стороны IDEA Intellij.

2024-10-21 00:46 UTC, DJettt commented on src/main/java/ru/urfu/logics/mathmechbot/states/DefaultState.java
> +    public void processMessage(@NotNull MathMechBotCore context, @NotNull Request request) {
Переименовали context -> contextCore.

2024-10-21 01:19 UTC, DJettt commented on src/main/java/ru/urfu/bots/DiscordBot.java
> +        //TODO: проверить на возникновение исключений
Исключения не возникнут.

2024-10-21 01:22 UTC, DJettt commented on src/main/java/ru/urfu/bots/DiscordBot.java
> +                .setActivity(Activity.playing("IDEA Intellij"))
В данном случае мы устанавливали статус бота в самом Дискорд. После запуска программы около бота было написано "играет в IDEA Intellij". 
В любом случае мы убрали этот статус в исправлениях.

2024-10-21 02:23 UTC, DJettt commented on src/main/java/ru/urfu/logics/mathmechbot/Constants.java
> +            .text("Сперва нужно зарегистрироваться.").build();
Сложность заключается в выборе - либо мы превращаем LocalMessage из record в обычный class и там добавляем огромное количество геттеров и конструктор с одним параметром, либо делаем что-то с LocalMessageBuilder. Данный класс (LocalMessageBuilder) в последствии будет более удобен для нас, поскольку нам нужно добавить обработку картинок и видео и при создании LocalMessage мы сразу сможем устанавливать нужные нам поля.
Ну то есть либо написать гигантский класс с тривиальными методами и JavaDoc-ами, либо писать чуть больше слов и символов при вызове билдера.
Мы будем рады если Вы нам подскажете что лучше сделать в данном случае :)

2024-10-21 03:12 UTC, ASHGOLDOFFICIAL commented on src/main/java/ru/urfu/logics/mathmechbot/MathMechBotCore.java
> +            assert getStorage().getUsers().get(request.id()).isPresent();
Ну, фактически IDEA права. Нет никакой гарантии,, что никто не удалил объект после того, как мы положили объект в хранилище, и перед тем, как мы его оттуда вытащали. Нам помогает то, что User'ов мы только создаём. Нигде не должно вызываться методов по их удалению. Но в любом случае, приведённое вами решение убирает потребность в assert.

2024-10-21 03:16 UTC, ASHGOLDOFFICIAL commented on src/main/java/ru/urfu/logics/mathmechbot/models/UserEntryBuilder.java
> +public final class UserEntryBuilder {
Ничего не придумал. Поэтому прошу вашего совета о том, как это сделать без static.

2024-10-21 03:21 UTC, ASHGOLDOFFICIAL commented on src/main/java/ru/urfu/logics/mathmechbot/states/MathMechBotState.java
> +     * TODO: сделать умнее.
4f1f3a0176c94e76dabde18c2bccb516778859c4

2024-10-21 03:32 UTC, ASHGOLDOFFICIAL commented on src/main/java/ru/urfu/logics/mathmechbot/states/editing/EditingFullNameState.java
> +        // TODO: Проверить более сложные имена, содержащие дефисы или несколько слов.
30aa462b317b4922cedffa04d2615d997357f3e9

2024-10-21 07:00 UTC, DJettt commented on src/main/java/ru/urfu/logics/mathmechbot/models/UserBuilder.java
> +    public UserBuilder(@NotNull Long id, @NotNull MathMechBotUserState currentState) {
Исправлено.
8789f6f2cf8a626bd4afecb7ce1c82ee90434e84

2024-10-21 11:25 UTC, ASHGOLDOFFICIAL commented on src/main/java/ru/urfu/logics/mathmechbot/storages/UserStorage.java
> +        update(new UserBuilder(id, state).build());
А как, вообще, тогда корректно использовать дефолтные методы?

А интерфейс создавали для того, что бы реализовывать его с помощью ArrayStorage или иной реализации Storage, потому что повторюсь: данный код сам по себе ничего не делает. Если бы я переделал его в класс, он бы не запустился даже, так как требовал бы реализации используемых и неиспользуемых get, getAll, add, update, delete.

2024-10-22 01:25 UTC, DJettt commented on src/main/java/ru/urfu/localobjects/Request.java
> +        @NotNull Bot bot
Пока что решили оставить это название, поскольку так проще работать с ядром. Согласен с Андреем по поводу "Request -- это запрос бота ядру".

2024-10-22 01:30 UTC, DJettt commented on src/main/java/ru/urfu/localobjects/LocalMessageBuilder.java
> +public final class LocalMessageBuilder {
da0d034721e24b3d6b7997626c843556d8cf2f94
Был добавлен конструктор в LocalMessage и исправлены подобные моменты в коде.

2024-10-22 01:36 UTC, DJettt commented on src/main/java/ru/urfu/logics/mathmechbot/storages/UserStorage.java
> +        update(new UserBuilder(id, state).build());
Нам интересно услышать Ваш ответ на наш вопрос, но в любом случае это было изменено в этом коммите:
6fd51b66437d062d93fdfb446e3d660992c1c016

2024-10-22 01:39 UTC, DJettt commented on src/main/java/ru/urfu/logics/mathmechbot/storages/UserEntryStorage.java
> +    default void changeUserEntryNameSurname(@NotNull Long id, @NotNull List<String> strings) {
6fd51b66437d062d93fdfb446e3d660992c1c016
Изменено. Реализации методов были перенесены в соответствующие классы.

2024-10-22 01:57 UTC, DJettt commented on src/main/java/ru/urfu/logics/LogicCore.java
> +    void processMessage(@NotNull Request request);
С точки зрения абстракции с этим не сложно работать и такой вариант реализации вполне простой, так как в запросе есть вся информация, которая нужна ядру при общении с пользователем.
id - идентификатор чата.
LocalMessage - само сообщение  bot->core.
Bot - информация о том, откуда пришло сообщение / куда отправить сообщение.

То есть request - запрос от бота к ядру
LocalMessage - содержимое запроса (сообщение от пользователя)
bot - отправитель запроса / адресат запроса

2024-10-25 12:09 UTC, DJettt commented on src/main/java/ru/urfu/logics/LogicCore.java
> +    void processMessage(@NotNull Request request);
24e487069342e2adfe768c43ec1010354f1298a6
Убрана зависимость в виде объекта Request

2024-10-25 12:11 UTC, DJettt commented on src/main/java/ru/urfu/localobjects/LocalMessageBuilder.java
> +public final class LocalMessageBuilder {
Я обсудил это с Вами на паре, Вы убедились, что без static тут не обойтись. В итоге было решено оставить билдер в другом классе.

2024-10-25 12:16 UTC, DJettt commented on src/main/java/ru/urfu/logics/mathmechbot/models/UserEntryBuilder.java
> +public final class UserEntryBuilder {
То же самое, что и с LocalMessageBuilder. Было решено оставить все как есть, чтобы не использовать static.

2024-10-25 12:18 UTC, DJettt commented on src/main/java/ru/urfu/logics/mathmechbot/states/DefaultState.java
> +            context.getStorage().getUsers().changeUserState(request.id(), MathMechBotUserState.REGISTRATION_NAME);
Было решено перенести решение этой проблемы в task-3

2024-10-25 12:22 UTC, DJettt commented on src/test/java/ru/urfu/logics/mathmechbot/editing/EditingTest.java
> +                new UserBuilder(0L, MathMechBotUserState.EDITING_FULL_NAME).build(),
65c1c9ee8da3e9a2d02fbef6cee7633c7d74d310

2024-10-28 20:54 UTC, vpyzhyanov commented on src/main/java/ru/urfu/Main.java
>      private static void startBot(LogicCore logicCore, String env, Class<? extends Bot> botClass) {
лучше словами пишите что именно изменили, отдельные коммиты никто смотреть не будет

2024-10-28 21:02 UTC, vpyzhyanov commented on src/main/java/ru/urfu/bots/TelegramBot.java
> +                LOGGER.error("Bot didn't get registered and didn't run.", e);
Так себе аргумент. Действительно, половина приложения не запустилась, ну и ладно, пусть пользователи пользуются тем, что запустилось сегодня, может завтра другое запуститься.......

2024-10-28 21:05 UTC, vpyzhyanov commented on src/main/java/ru/urfu/localobjects/Request.java
> +        long id,
Вы не поняли, речь про аннотацию `@NotNull`, а идентификатор единственное поле, которое ей не помечено, значит оно может быть null

2024-10-28 21:07 UTC, vpyzhyanov commented on src/main/java/ru/urfu/localobjects/Request.java
> +        @NotNull Bot bot
обсудили на паре и не нашли ничего удобного в классе Request

2024-10-28 21:10 UTC, vpyzhyanov commented on src/main/java/ru/urfu/logics/mathmechbot/MathMechBotCore.java
> +            assert getStorage().getUsers().get(request.id()).isPresent();
научитесь создавать переменные и не делать одинаковые действия, тогда и лишних предупреждений не будет

2024-10-28 21:13 UTC, vpyzhyanov commented on src/main/java/ru/urfu/logics/mathmechbot/MathMechBotCore.java
> +    public MathMechStorage getStorage() {
обсудили на паре. Исправления не последовало(

2024-10-28 21:15 UTC, vpyzhyanov commented on src/main/java/ru/urfu/logics/mathmechbot/MathMechBotCore.java
> +        currentState.processMessage(this, request);
тоже обсудили на паре

2024-10-28 21:15 UTC, vpyzhyanov commented on src/main/java/ru/urfu/logics/mathmechbot/MathMechBotCore.java
> +        currentState.processMessage(this, request);
Не забывайте описать результат договорённости

2024-10-28 21:17 UTC, vpyzhyanov commented on src/main/java/ru/urfu/logics/mathmechbot/states/DefaultState.java
> +    public void processMessage(@NotNull MathMechBotCore context, @NotNull Request request) {
Лучше не стало. Если бездумно применять паттерн, то ничего полезного из него не выйдет

2024-10-28 21:22 UTC, vpyzhyanov commented on src/main/java/ru/urfu/storages/ArrayStorage.java
> +    private final ArrayList<T> array;
Замечание пишется на конкретную строку, она самая нижняя. Верхние - приведены для контекста

2024-10-28 21:23 UTC, vpyzhyanov commented on src/main/java/ru/urfu/logics/mathmechbot/storages/UserStorage.java
> +        update(new UserBuilder(id, state).build());
ответил на паре

2024-10-28 21:31 UTC, vpyzhyanov commented on src/main/java/ru/urfu/logics/mathmechbot/storages/UserEntryStorage.java
> +    default void changeUserEntryNameSurname(@NotNull Long id, @NotNull List<String> strings) {
> Дополнительные методы в UserEntryStorage по редактированию отдельных полей были добавлены, так как я считаю, что за изменение полей должно отвечать хранилище. Ну, в случае с БД, мы данные редактируем в ней, а не вне её. Изменение выгруженных данных не влечёт изменения их в постоянном хранилище. Только если менять их напрямую в БД они будут меняться. Поэтому эти методы и были назначены Storage'ам, как часть их ответственности.

Я вам про Фому, а вы мне про Ерёму. Такими темпами вы точно ничему не научитесь. Сначала надо научиться слышать и читать. Потом научиться задавать вопросы. Далее можно будет научиться чему угодно. А пока вы не читаете замечания и пишете совершенно не связанные с ним вещи, ничего исправить и чему-то научиться точно не получится. Будете и дальше создавать совершенно бессмысленные классы вроде UserEntryArrayStorage, у которого реализация методов в **интерфейсе**, кто бы мог подумать.

2024-10-28 21:34 UTC, vpyzhyanov commented on src/test/java/ru/urfu/logics/mathmechbot/DeleteCommandTest.java
> +    @DisplayName("Нажата кнопка 'Неа' во время подтверждения удаления данных")
или показывает, что разработчики безграмотные и приложение их не серьёзное, а шуточное, т.е. ничего полезного не делает. Не забывайте с разных сторон посмотреть на одни и те же вещи

2024-10-28 21:36 UTC, vpyzhyanov approved these changes
можете мёрджить

2024-10-28 22:13 UTC, merged