Подключение базы данных
DJettt/MathMechBot pull request #30
Opened 2024-11-22 02:08 UTC by DJettt

Используемая СУБД: **PostgreSQL_**
API для коннекта с СУБД: **JDBC**

### В базе данных используется 2 таблицы:

- **userentry** - таблица с данными о пользователе

- **users** - таблица с информацией о текущих состояниях пользователя

2024-11-25 09:29 UTC, ASHGOLDOFFICIAL requested changes

2024-11-25 09:29 UTC, ASHGOLDOFFICIAL commented on src/main/java/ru/urfu/mathmechbot/storages/MathMechStorageInterface.java
> +public interface MathMechStorageInterface {
Переименуй в MathMechStorage. Не стоит писать Interface, так как это явно и есть интерфейс. Лучше переименую реализацию интерфейса (MathMechStorage) в что-то типа MathMechDbStorage, так мы отразим особенность реализации.

2024-11-25 09:29 UTC, ASHGOLDOFFICIAL commented on src/main/java/ru/urfu/mathmechbot/storages/UserEntryCacheStorage.java
> +    final static float LOAD_FACTOR = 0.8f;
Пожалуйста, объясни, почему используется какой-то особенный load factor? Я вижу в документации, что этот параметр указывать необязательно, поэтому прошу объясни, почему мы используем какой-то особенный. И добавь комментарий внутрь кода с этим объяснением, чтобы рядом всегда можно было прочесть причину выбора.

2024-11-25 09:29 UTC, ASHGOLDOFFICIAL commented on src/main/java/ru/urfu/mathmechbot/storages/UserEntryCacheStorage.java
> +        cache.put(member.id(), member);
Надо проверить, вываливаемся ли мы за пределы кэша. У нас в постановке написано, что после 5000 тысяч записей (если я верно помню число), мы очищаем весь кэш и начинаем повторное заполнение. Пока что у нас кэш растёт неограниченно, что может быть причиной полного заполнения памяти. Поэтому, пожалуйста, реализуй этот функционал.

2024-11-25 09:29 UTC, ASHGOLDOFFICIAL commented on src/main/java/ru/urfu/mathmechbot/storages/UserEntryCacheStorage.java
> +        cache.put(member.id(), member);
Это фрагмент из JavaDoc для данного метода.

```
* Обновляет элемент в хранилище.<br/>
* Два элемента считаются одним и тем же, если их id совпадает.
```

Метод update должен только обновлять. Если метод update вызывается на несуществующий объект, то ничего произойти не должно. Это некоторое нарушение полиморфизма, так как реализация этого метода работает иначе, чем заявлено в интерфейсе. Кратко: перед тем, как делать put в cache надо проверить, а существует ли элемент, который мы хотим обновить. Иначе ничего делать не надо.

2024-11-25 09:29 UTC, ASHGOLDOFFICIAL commented on src/main/java/ru/urfu/mathmechbot/storages/UserEntryFullStorage.java
> +    final UserEntryCacheStorage cache = new UserEntryCacheStorage();
Прости, пожалуйста, ибо проверить сам сейчас не могу (не за своим ноутбуком), но можно ли тут вместо UserEntryCacheStorage и UserEntryPostgresStorage использовать интерфейс UserEntryStorage? Если ничего не сломается, предлагаю использовать именно интерфейсы. Ситуация аналогична той, когда мы пишем List вместо ArrayList.

2024-11-25 09:29 UTC, ASHGOLDOFFICIAL commented on src/main/java/ru/urfu/mathmechbot/storages/UserEntryFullStorage.java
> +        cache.delete(member);
Будь аккуратнее с cache.update() и cache.delete(). Напомню, что кэш у нас со временем очищаться должен (для ограничения используемой памяти). То есть в теории может возникнуть ситуация, где ты вызываешь эти методы, а в кэше нет нужных объектов. Вместо этого надо проверить, а есть ли эти элементы в кэше. Если их нет, надо их добавить туда.

2024-11-25 09:29 UTC, ASHGOLDOFFICIAL commented on src/main/java/ru/urfu/mathmechbot/storages/UserEntryPostgresStorage.java
> +    private final static String DELETE_INFO = "DELETE FROM userentry WHERE userid = ?";
Добавь ко всем именам переменных, которые содержат SQL-выражение, суффикс  "_QUERY" для ясности того, что именно это за строка.

2024-11-25 09:29 UTC, ASHGOLDOFFICIAL commented on src/main/java/ru/urfu/mathmechbot/storages/UserEntryPostgresStorage.java
> +    @SuppressWarnings("MultipleStringLiterals")
Вынеси строки в константы. Таким образом, можно избавиться от лишнего подавления, плюс это в данном случае полезно будет, так как действительно одна и та же строка повторяется много раз. Если захотим когда-то по какой-то причине изменить имя колонки, то придётся менять кучу её упоминаний. Так же нет защиты от опечаток. Короче, ворнинг, который ты подавил, на самом деле имеет место быть, так как говорит о возможности улучшить код.

2024-11-25 09:29 UTC, ASHGOLDOFFICIAL commented on src/main/java/ru/urfu/mathmechbot/storages/UserEntryPostgresStorage.java
> +                logger.error("Информация не удалена.");
Предлагаю использовать метод warn(), а не error(). Потому что существование ошибки здесь не гарантировано, но сама ситуация может быть результатом какой-то ошибки. Поэтому лучше "предупредить". 

Из документации: `The WARN level designates potentially harmful situations.`

2024-11-25 09:29 UTC, ASHGOLDOFFICIAL commented on src/main/java/ru/urfu/mathmechbot/storages/UserPostgresStorage.java
> +    private final static String CREATE_TABLE = """
Изучи, пожалуйста, опцию CREATE TABLE IF NOT EXISTS. Поверхностный поиск по Интернету сказал, что такой функционал есть в Postgres. Но я прошу тебя проверить, ибо сам пока не могу. Если такая опция действительно есть, лучше использовать её. Просто я не уверен, что произойдёт, если вызывать простой CREATE TABLE, когда таблица уже создана.

2024-11-25 09:29 UTC, ASHGOLDOFFICIAL commented on src/main/java/ru/urfu/mathmechbot/storages/UserPostgresStorage.java
> +        Long id = user.id();
Предлагаю в подобных случаях использовать примитив long вместо обёртки Long, если возможно.

2024-11-25 09:29 UTC, ASHGOLDOFFICIAL commented on src/main/java/ru/urfu/mathmechbot/storages/UserPostgresStorage.java
> +            return null;
Лучше прервать выполнение работы программы или попробовать снова. В противном случае этот null может поломать логику кода и стать причиной различных NullPointerException'ов. Лучше, думаю, null не возвращать в любом случае, а возвращать пустой список.

2024-11-25 09:29 UTC, ASHGOLDOFFICIAL commented on src/main/java/ru/urfu/mathmechbot/storages/converter/CurrentStateConverter.java
> + * Конвертирует строку из бд в конкретное состояние и наоборот.
Может лучше в БД всё-таки хранить не строку, которая весит много байт, а обычное число? И пусть этот класс сопоставляет число состоянию и наоборот. Это сэкономит нам памяти раз в 30--50, что почти даже не преувеличение.

2024-11-25 09:29 UTC, ASHGOLDOFFICIAL commented on src/main/java/ru/urfu/mathmechbot/storages/converter/CurrentStateConverter.java
> +            case UserState.REGISTRATION_NAME -> REGISTRATION_NAME;
Предлагаю просто заменить это на поиск в хэш-мапе. Поможет избавиться от чрезмерного количества case'ов в switch. Плюс поиск по хэш-мапе, вроде как, быстрее. Дальше состояний будет становиться только больше, что также усложнит метод. Хэш-мапы можно создавать в конструкторе. Возможно, что строить хэш-мапу лучше на основании содержимого некоторого файла, но выгода этого решения ещё под вопросом.

2024-11-25 09:29 UTC, ASHGOLDOFFICIAL commented on src/main/java/ru/urfu/mathmechbot/storages/converter/CurrentStateConverter.java
> +    @SuppressWarnings("CyclomaticComplexity")
Пожалуйста, избегай подавлений ворнингов. Они возникают не просто так. Они говорят о том, что в нашем коде потенциально что-то не так. Подавление -- это крайний случай, когда нет иного решения. В данном случае проблема действительно есть: гигантский switch, который дальше будет только расти.

2024-11-25 09:29 UTC, ASHGOLDOFFICIAL commented on src/main/java/ru/urfu/mathmechbot/storages/converter/CurrentStateConverter.java
> +            case UserState.REGISTRATION_NAME -> REGISTRATION_NAME;
Поизучай, кстати, про что-то типа биекционных отображений (би-мап). Грубо говоря, мапа, где значение тоже может быть ключом. В таком случае мы построим одну мапу (отображение) и уменьшим число потенциальных ошибок. Не помню точно, есть ли она в Java по умолчанию, но если нет, то можно найти библиотеку с ней.

2024-11-25 09:29 UTC, ASHGOLDOFFICIAL commented on pom.xml
> +            <version>42.7.4</version>
Используй тут переменную, а не хардкоженное значение. Переменную, я видел, ты уже вынес, осталось только сюда вставить.

2024-11-25 09:29 UTC, ASHGOLDOFFICIAL commented on src/main/java/ru/urfu/mathmechbot/storages/UserEntryCacheStorage.java
> + * Содержит в себе всю информацию о пользователях.
Слово "всю" здесь лишнее, так как кэш может и должен очищаться. То есть не всегда здесь содержится вся информация.

2024-11-25 09:29 UTC, ASHGOLDOFFICIAL commented on src/main/java/ru/urfu/mathmechbot/storages/UserEntryCacheStorage.java
> +    final static int INITIAL_CAPACITY = 5000;
Сделай их приватными, а то у меня есть опасения, что они сейчас package-private.

2024-11-25 09:29 UTC, ASHGOLDOFFICIAL commented on src/main/java/ru/urfu/mathmechbot/storages/UserEntryCacheStorage.java
> +        cache.put(id, new UserEntryBuilder(cache.get(id))
Мне кажется, что я, возможно, это где-то писал уже, но на всякий случай повторясь. Нет гарантии, что данный элемент лежит в кэше. Поэтому  cache.get() может ничего не вернуть. В таком случае кэш может быть инвалиден, так как в БД одна информация, а в кэше — другая.

2024-11-25 09:29 UTC, ASHGOLDOFFICIAL commented on src/main/java/ru/urfu/mathmechbot/storages/UserEntryPostgresStorage.java
> +    private final static String LOG_ERROR_UNTIL_UPDATE = "Информация не обновлена.";
"Log error until update" переводится как "Ошибка до тех пор, пока не обновиться". Я не совсем понимаю, что тут имелось в виду. Если судить по содержимому строки, то лучше назвать примерно `LOG_INFORMATION_UPDATE_FAILED` (лог обновление информации провалилось).

2024-11-25 09:29 UTC, ASHGOLDOFFICIAL commented on src/main/java/ru/urfu/mathmechbot/storages/UserEntryPostgresStorage.java
> +    //TODO было бы классно выделить всю структуру таблицы в отдельный файл, возможно properties
От TODO стоит избавиться. Либо реализуй желаемое, либо убери его. Наш PR с TODO, скорее всего, не пустят, как это было в прошлый раз.

2024-11-25 09:29 UTC, ASHGOLDOFFICIAL commented on src/main/java/ru/urfu/mathmechbot/storages/UserEntryPostgresStorage.java
> +    private final static String TABLE_NAME = "userentry";
Ты назвал таблицу пользователей "users" (множественное число). Тогда назови во множественном числе и эту таблицу для единообразия кода. Множественное число: "userentries".

2024-11-25 09:29 UTC, ASHGOLDOFFICIAL commented on src/main/java/ru/urfu/mathmechbot/storages/UserEntryPostgresStorage.java
> +                listUserEntry.add(new UserEntryBuilder(results.getLong("userid"), results.getLong("userid"))
Вынеси превращение строки из БД (ResultSet) в UserEntry в отдельный метод. Так повысим читабельность кода. Плюс, потенциально может возникнуть ситуация, где мы будем это превращение делать несколько раз, тогда вынесением в отдельный метод мы сократим число повторений блоков кода.

2024-11-25 09:29 UTC, ASHGOLDOFFICIAL commented on src/main/java/ru/urfu/mathmechbot/storages/UserEntryPostgresStorage.java
> +            preparedStatement.setString(SET_FIRST, userEntry.surname());
Блок кода с заполнением запроса содержимым UserEntry повторяется уже дважды. Предлагаю вынести в отдельный метод.

2024-11-25 09:29 UTC, ASHGOLDOFFICIAL commented on src/main/java/ru/urfu/mathmechbot/storages/UserEntryPostgresStorage.java
> +            if (userEntry.year() != null) {
Почему проверка на null начинается только с года. Среди предыдущих полей же тоже могут быть nullable. Если что, я не прошу ничего менять, а просто объяснения, чтобы самому работу кода понять.

2024-11-25 09:29 UTC, ASHGOLDOFFICIAL commented on src/main/java/ru/urfu/mathmechbot/storages/UserEntryPostgresStorage.java
> +                logger.error(LOG_ERROR_UNTIL_UPDATE);
Предлагаю снова warn(). Можно как правило пальца использовать следующую логику: если ты кидаешь исключение, то логируй через error(). Иначе просто предупреждай через warn().

2024-11-25 09:29 UTC, ASHGOLDOFFICIAL commented on src/main/java/ru/urfu/mathmechbot/storages/UserPostgresStorage.java
> +            id BIGINT,
Мне кажется, тут нужно указать, что это главный ключ.

2024-11-25 09:29 UTC, ASHGOLDOFFICIAL commented on src/main/java/ru/urfu/mathmechbot/storages/UserPostgresStorage.java
> +            preparedStatement.setLong(SET_FIRST, id);
Вновь предлагаю вынести подготовку запроса в отдельный метод.

2024-11-25 09:29 UTC, ASHGOLDOFFICIAL commented on src/main/java/ru/urfu/mathmechbot/storages/UserPostgresStorage.java
> +            this.add(newUser);
Этим должна заниматься логика программы, а не хранилище данных. Она этим, в принципе, и занимается уже. Если кратко, хранилище не должно решать когда ему пользователя добавлять внутрь.

Это нарушение полиморфизма. Метод get() должен только возвращать. Если ничего не находит он, то он и возвращает пустой Optional. Сейчас этот метод начал выполнять постороннюю логику, о которой не было упомянуто в JavaDoc'ах интерфейса.

Банальный пример: логика может решить не добавлять пользователя в БД. Но сейчас она такое решение сделать не может, потому что это решение принимает этот класс.

Короче, get должен только получать. Ничего писать он не должен, тем более, когда интерфейс не говорит об этом.

2024-11-25 09:29 UTC, ASHGOLDOFFICIAL commented on src/main/java/ru/urfu/mathmechbot/storages/UserPostgresStorage.java
> +                        Objects.requireNonNull(converter.convert(result.getString(CURRENT_STATE_STRING)))));
Мне кажется, конвертер не должен возвращать null вообще. У каждого пользователя есть какое-то состояние. Это должно гарантироваться логикой. Если возникла противоположная ситуация, то она ошибочна. Поэтому повесь NotNull в конвертере и не возвращай null.

2024-11-25 09:29 UTC, ASHGOLDOFFICIAL commented on src/main/java/ru/urfu/mathmechbot/storages/UserPostgresStorage.java
> +        List<User> newList = new ArrayList<User>();
newList -> ~users

Желательно, чтобы название отражало суть содержимого.

2024-11-25 09:29 UTC, ASHGOLDOFFICIAL commented on src/main/java/ru/urfu/mathmechbot/storages/UserPostgresStorage.java
> +            logger.error("Ошибка при удалении данных в таблице.");
Кидай исключение в этом и всех подобных случаях.

2024-11-25 09:29 UTC, ASHGOLDOFFICIAL commented on src/main/java/ru/urfu/mathmechbot/storages/postgresql/ConnectionManager.java
> +    private final static String PASSWORD = "db.password";
Всё-таки попрошу перейти на переменные окружения. Этот способ упростит запуск и развёртывание Docker. Как я понял, кстати, у нас дедлайн на допзадачи до 2-го декабря. То есть надо уже сегодня желательно деплоить. Поэтому, пожалуйста, подготовь код к Docker и проведи ревью PR с ним.

2024-11-26 04:04 UTC, DJettt commented on src/main/java/ru/urfu/mathmechbot/storages/converter/CurrentStateConverter.java
> + * Конвертирует строку из бд в конкретное состояние и наоборот.
Планирую это сделать потом как дополнительная оптимизация.

2024-11-26 05:13 UTC, ASHGOLDOFFICIAL reviewed
Передавай во все ошибки ещё и само пойманное исключение. Там можно вторым аргументом это сделать.

2024-11-26 05:33 UTC, DJettt commented on src/main/java/ru/urfu/mathmechbot/storages/UserEntryFullStorage.java
> +    final UserEntryCacheStorage cache = new UserEntryCacheStorage();
Да, можно

2024-11-26 06:45 UTC, DJettt commented on src/main/java/ru/urfu/mathmechbot/storages/UserEntryPostgresStorage.java
> +                logger.error("Информация не удалена.");
de635cd30ed1d9c127791c77ae9649e0ee1b94e1

2024-11-26 06:45 UTC, DJettt commented on src/main/java/ru/urfu/mathmechbot/storages/MathMechStorageInterface.java
> +public interface MathMechStorageInterface {
de635cd30ed1d9c127791c77ae9649e0ee1b94e1

2024-11-26 06:45 UTC, DJettt commented on src/main/java/ru/urfu/mathmechbot/storages/UserEntryCacheStorage.java
> +    final static float LOAD_FACTOR = 0.8f;
de635cd30ed1d9c127791c77ae9649e0ee1b94e1

2024-11-26 06:45 UTC, DJettt commented on src/main/java/ru/urfu/mathmechbot/storages/UserEntryCacheStorage.java
> +        cache.put(member.id(), member);
de635cd30ed1d9c127791c77ae9649e0ee1b94e1

2024-11-26 06:45 UTC, DJettt commented on src/main/java/ru/urfu/mathmechbot/storages/UserEntryCacheStorage.java
> +        cache.put(member.id(), member);
de635cd30ed1d9c127791c77ae9649e0ee1b94e1

2024-11-26 06:45 UTC, DJettt commented on src/main/java/ru/urfu/mathmechbot/storages/UserEntryFullStorage.java
> +    final UserEntryCacheStorage cache = new UserEntryCacheStorage();
de635cd30ed1d9c127791c77ae9649e0ee1b94e1

2024-11-26 06:45 UTC, DJettt commented on src/main/java/ru/urfu/mathmechbot/storages/UserEntryFullStorage.java
> +        cache.delete(member);
de635cd30ed1d9c127791c77ae9649e0ee1b94e1

2024-11-26 06:45 UTC, DJettt commented on src/main/java/ru/urfu/mathmechbot/storages/UserEntryPostgresStorage.java
> +    private final static String DELETE_INFO = "DELETE FROM userentry WHERE userid = ?";
de635cd30ed1d9c127791c77ae9649e0ee1b94e1

2024-11-26 06:45 UTC, DJettt commented on src/main/java/ru/urfu/mathmechbot/storages/UserEntryPostgresStorage.java
> +    @SuppressWarnings("MultipleStringLiterals")
de635cd30ed1d9c127791c77ae9649e0ee1b94e1

2024-11-26 06:45 UTC, DJettt commented on src/main/java/ru/urfu/mathmechbot/storages/UserEntryPostgresStorage.java
> +                logger.error("Информация не удалена.");
de635cd30ed1d9c127791c77ae9649e0ee1b94e1

2024-11-26 06:45 UTC, DJettt commented on src/main/java/ru/urfu/mathmechbot/storages/UserPostgresStorage.java
> +    private final static String CREATE_TABLE = """
de635cd30ed1d9c127791c77ae9649e0ee1b94e1

2024-11-26 06:45 UTC, DJettt commented on src/main/java/ru/urfu/mathmechbot/storages/UserPostgresStorage.java
> +        Long id = user.id();
de635cd30ed1d9c127791c77ae9649e0ee1b94e1

2024-11-26 06:45 UTC, DJettt commented on src/main/java/ru/urfu/mathmechbot/storages/UserPostgresStorage.java
> +            return null;
de635cd30ed1d9c127791c77ae9649e0ee1b94e1

2024-11-26 06:46 UTC, DJettt commented on src/main/java/ru/urfu/mathmechbot/storages/converter/CurrentStateConverter.java
> +            case UserState.REGISTRATION_NAME -> REGISTRATION_NAME;
de635cd30ed1d9c127791c77ae9649e0ee1b94e1

2024-11-26 06:46 UTC, DJettt commented on src/main/java/ru/urfu/mathmechbot/storages/converter/CurrentStateConverter.java
> +    @SuppressWarnings("CyclomaticComplexity")
de635cd30ed1d9c127791c77ae9649e0ee1b94e1

2024-11-26 06:46 UTC, DJettt commented on pom.xml
> +            <version>42.7.4</version>
de635cd30ed1d9c127791c77ae9649e0ee1b94e1

2024-11-26 06:46 UTC, DJettt commented on src/main/java/ru/urfu/mathmechbot/storages/UserEntryCacheStorage.java
> + * Содержит в себе всю информацию о пользователях.
de635cd30ed1d9c127791c77ae9649e0ee1b94e1

2024-11-26 06:46 UTC, DJettt commented on src/main/java/ru/urfu/mathmechbot/storages/UserEntryCacheStorage.java
> +    final static int INITIAL_CAPACITY = 5000;
de635cd30ed1d9c127791c77ae9649e0ee1b94e1

2024-11-26 06:46 UTC, DJettt commented on src/main/java/ru/urfu/mathmechbot/storages/UserEntryCacheStorage.java
> +        cache.put(id, new UserEntryBuilder(cache.get(id))
de635cd30ed1d9c127791c77ae9649e0ee1b94e1

2024-11-26 06:46 UTC, DJettt commented on src/main/java/ru/urfu/mathmechbot/storages/UserEntryPostgresStorage.java
> +    //TODO было бы классно выделить всю структуру таблицы в отдельный файл, возможно properties
de635cd30ed1d9c127791c77ae9649e0ee1b94e1

2024-11-26 07:58 UTC, ASHGOLDOFFICIAL approved these changes
Окей. Сливай.

2024-11-26 07:58 UTC, merged